language: node_js
node_js:
    - stable
deploy:
    provider: npm
    email: arsovik@gmail.com
    api_key:
        secure: ew7UD47Cm85eARXV95TNypaALezW+5ezd3hAOomc/7JFNK45Qdaxz9U/3CAdsWnB4PbrpJEIWYpkKVuI9TB2361yUXS8j9/mfht7xGOGrPxFooY9nWH/aDmytziEX2EGuTH62fWawsXgh0ibAPdX5x0lJCdS8jtGPGYb7tkZyX85SEQTrhs/g9MKG8+AFURXN+IZSMXdVV9d8/MY0ICz5Oznrp775ndobvSaPRD92oDrfpBfkavgzgCy6nhPH+Rp9Ap1LGtivY458hvGfEVjbCZmoN/onitAFAJ7fp+jizyQCZmXgWyDaAUvOSTs8l0ZtSPVtmNM0xy8hXWdnqDtdNL8WwwbOtdCKGJcV1YeMBusouuvxNhmz/zXr2YaoFEQTw0vpPk0BgwOAp8wAS59Q6PElCWZTQzNlbxuQkVUP9AVVgqLZg0sn96vu7HvVSG0BZOIrtJt0u4AEeBuFKvEgvgcKCNuGnSlxlZOKQ71ZFQhusW1wcoZ8xEIYnIXU7Er18y5PTwrqlfNX9cqradaCvnDlbJ9Ce5gDI1fGkvptapnUS8fV3Q3pSc4LphalclntVDUDrarrVZiaMs+2dA+c7B0FndtT7rNsvS0NLdmjEdGyKGl5FulJnzMGGcDQQ0XS9KocBibgLLro0NyGfOIUC6yx7zrPyQtRPCP7cbgzIo=
    on:
        tags: true
addons:
    code_climate:
        repo_token:
            secure: F6rXHVV7Wlben5K5E0MlAqZ6bewCu7EhgebnQ9UXmSEYvyoNbFzgkoIvhHEbMF4amFJgS8hdJrF6GqtiS9fLFs5wp/OQDJhxjdP6Lf7PKzT+3ZPZoBOWnrL/041Y9JKsAwEi07jRvHfkMDduKqrct39M96WC3EVgfGtNZ1yPk9Oq5LvexztJDeXxMzRan8PwzfLcps4ifSnkMcrs1hu6HqJ5ac358ai3bn1mTMfVDr/CGN1FDnqF9MKSNznuBNjcluotaCKu7o8w6+5Q5wVMZWBFcW0LzGwvPvo8WpU/ChIw5k9GoXthytoaGxDOf58XY+VSnL3NSwPjGIfi+A3+YHh9km2yqEkdkfhcNvnGQ4u5BQzeZm0m+5O6Qsy4QWNl38XU/Mh+e5FkKrAdxBrmceX45mZdCyusyQwUPX17a2lpHPMmRhm4kNAqkywawxkKOhKRjqKQ9Wr0mYW9Vmfa6jH48PXVudoobuvOilN80g8/+xOxqV8IXWUE6ybFv8pBDIgQcYgm4Fc7w5VE78Ar2sEeXQf3SlnDXu6FIYESNxpNm/O4UloKOEWCWSv0OwtEm0b9I35BNZl614A/un+1UU7JPJwL3rBFqPHvsefA5c+herl5gPvyBism5K2TtJ76yJM8WLIBwkrbOFdSvdy097TZ4SAneQ7d3jMB8f9VDck=
after_script:
    - codeclimate-test-reporter < coverage/lcov.info
    - cat coverage/lcov.info | node_modules/.bin/coveralls
